### prometheus configuration file for prometheus server kubernetes deployment
global:
  external_labels: null
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

remote_write:
  - url: "https://pweshmark01.grafana.net/datasources/edit/grafanacloud-prom"
    basic_auth:
      username: "1001215"
      password_file: /etc/config/grafana-secret/password


scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  # - job_name: "kubernetes-nodes"
  #   scheme: http
  #   tls_config:
  #     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  #   authorization:
  #     credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #   kubernetes_sd_configs:
  #     - role: node
  #   relabel_configs:
  #     - action: labelmap
  #       regex: __meta_kubernetes_node_label_(.+)


  # - job_name: "kubernetes-service-endpoints"
  #   kubernetes_sd_configs:
  #     - role: endpoints
  #   relabel_configs:
  #     - action: labelmap
  #       regex: __meta_kubernetes_service_label_(.+)
  #     - source_labels: [__meta_kubernetes_namespace]
  #       action: replace
  #       target_label: namespace
  #     - source_labels: [__meta_kubernetes_service_name]
  #       action: replace
  #       target_label: service


  # - job_name: "kubernetes-pods"
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - action: labelmap
  #       regex: __meta_kubernetes_pod_label_(.+)
  #     - source_labels: [__meta_kubernetes_namespace]
  #       action: replace
  #       target_label: namespace
  #     - source_labels: [__meta_kubernetes_pod_name]
  #       action: replace
  #       target_label: pod

