name: 'Terraform'

on:
  # push:
  #   branches:
  #   - main
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      Approved:
        required: true
        description: 'Has the Terraform code been approved?'
        default: 'False'
        type: choice
        options:
        - True
        - False

jobs:
  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    if: github.ref == 'refs/heads/terraform' && github.event_name == 'pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}  
        export_default_credentials: true

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: |
       terraform apply -auto-approve
